# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zoltan/Develop/alaska/alaska-asplos24-artifact

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zoltan/Develop/alaska/alaska-asplos24-artifact

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Alaska\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoltan/Develop/alaska/alaska-asplos24-artifact/CMakeFiles /home/zoltan/Develop/alaska/alaska-asplos24-artifact//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zoltan/Develop/alaska/alaska-asplos24-artifact/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named venv

# Build rule for target.
venv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 venv
.PHONY : venv

# fast build rule for target.
venv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/venv.dir/build.make CMakeFiles/venv.dir/build
.PHONY : venv/fast

#=============================================================================
# Target rules for targets named redis_alaska

# Build rule for target.
redis_alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis_alaska
.PHONY : redis_alaska

# fast build rule for target.
redis_alaska/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_alaska.dir/build.make CMakeFiles/redis_alaska.dir/build
.PHONY : redis_alaska/fast

#=============================================================================
# Target rules for targets named memcached_alaska

# Build rule for target.
memcached_alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memcached_alaska
.PHONY : memcached_alaska

# fast build rule for target.
memcached_alaska/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memcached_alaska.dir/build.make CMakeFiles/memcached_alaska.dir/build
.PHONY : memcached_alaska/fast

#=============================================================================
# Target rules for targets named figure7_csv

# Build rule for target.
figure7_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure7_csv
.PHONY : figure7_csv

# fast build rule for target.
figure7_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure7_csv.dir/build.make CMakeFiles/figure7_csv.dir/build
.PHONY : figure7_csv/fast

#=============================================================================
# Target rules for targets named figure7_pdf

# Build rule for target.
figure7_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure7_pdf
.PHONY : figure7_pdf

# fast build rule for target.
figure7_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure7_pdf.dir/build.make CMakeFiles/figure7_pdf.dir/build
.PHONY : figure7_pdf/fast

#=============================================================================
# Target rules for targets named figure8_csv

# Build rule for target.
figure8_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure8_csv
.PHONY : figure8_csv

# fast build rule for target.
figure8_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure8_csv.dir/build.make CMakeFiles/figure8_csv.dir/build
.PHONY : figure8_csv/fast

#=============================================================================
# Target rules for targets named figure8_pdf

# Build rule for target.
figure8_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure8_pdf
.PHONY : figure8_pdf

# fast build rule for target.
figure8_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure8_pdf.dir/build.make CMakeFiles/figure8_pdf.dir/build
.PHONY : figure8_pdf/fast

#=============================================================================
# Target rules for targets named rsstracker

# Build rule for target.
rsstracker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rsstracker
.PHONY : rsstracker

# fast build rule for target.
rsstracker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsstracker.dir/build.make CMakeFiles/rsstracker.dir/build
.PHONY : rsstracker/fast

#=============================================================================
# Target rules for targets named figure9_pdf

# Build rule for target.
figure9_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure9_pdf
.PHONY : figure9_pdf

# fast build rule for target.
figure9_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure9_pdf.dir/build.make CMakeFiles/figure9_pdf.dir/build
.PHONY : figure9_pdf/fast

#=============================================================================
# Target rules for targets named figure10_pdf

# Build rule for target.
figure10_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure10_pdf
.PHONY : figure10_pdf

# fast build rule for target.
figure10_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure10_pdf.dir/build.make CMakeFiles/figure10_pdf.dir/build
.PHONY : figure10_pdf/fast

#=============================================================================
# Target rules for targets named redis_alaska_large_csv

# Build rule for target.
redis_alaska_large_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis_alaska_large_csv
.PHONY : redis_alaska_large_csv

# fast build rule for target.
redis_alaska_large_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_alaska_large_csv.dir/build.make CMakeFiles/redis_alaska_large_csv.dir/build
.PHONY : redis_alaska_large_csv/fast

#=============================================================================
# Target rules for targets named figure11_pdf

# Build rule for target.
figure11_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure11_pdf
.PHONY : figure11_pdf

# fast build rule for target.
figure11_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure11_pdf.dir/build.make CMakeFiles/figure11_pdf.dir/build
.PHONY : figure11_pdf/fast

#=============================================================================
# Target rules for targets named memcached_sweep_csv

# Build rule for target.
memcached_sweep_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memcached_sweep_csv
.PHONY : memcached_sweep_csv

# fast build rule for target.
memcached_sweep_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memcached_sweep_csv.dir/build.make CMakeFiles/memcached_sweep_csv.dir/build
.PHONY : memcached_sweep_csv/fast

#=============================================================================
# Target rules for targets named figure12_pdf

# Build rule for target.
figure12_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure12_pdf
.PHONY : figure12_pdf

# fast build rule for target.
figure12_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure12_pdf.dir/build.make CMakeFiles/figure12_pdf.dir/build
.PHONY : figure12_pdf/fast

#=============================================================================
# Target rules for targets named alaska_core_objects

# Build rule for target.
alaska_core_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_core_objects
.PHONY : alaska_core_objects

# fast build rule for target.
alaska_core_objects/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_core_objects.dir/build.make runtime/CMakeFiles/alaska_core_objects.dir/build
.PHONY : alaska_core_objects/fast

#=============================================================================
# Target rules for targets named alaska_core

# Build rule for target.
alaska_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_core
.PHONY : alaska_core

# fast build rule for target.
alaska_core/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_core.dir/build.make runtime/CMakeFiles/alaska_core.dir/build
.PHONY : alaska_core/fast

#=============================================================================
# Target rules for targets named alaska_core_static

# Build rule for target.
alaska_core_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_core_static
.PHONY : alaska_core_static

# fast build rule for target.
alaska_core_static/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_core_static.dir/build.make runtime/CMakeFiles/alaska_core_static.dir/build
.PHONY : alaska_core_static/fast

#=============================================================================
# Target rules for targets named alaska_sim

# Build rule for target.
alaska_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_sim
.PHONY : alaska_sim

# fast build rule for target.
alaska_sim/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_sim.dir/build.make runtime/CMakeFiles/alaska_sim.dir/build
.PHONY : alaska_sim/fast

#=============================================================================
# Target rules for targets named alaska

# Build rule for target.
alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska
.PHONY : alaska

# fast build rule for target.
alaska/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska.dir/build.make runtime/CMakeFiles/alaska.dir/build
.PHONY : alaska/fast

#=============================================================================
# Target rules for targets named lifetimemalloc

# Build rule for target.
lifetimemalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lifetimemalloc
.PHONY : lifetimemalloc

# fast build rule for target.
lifetimemalloc/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/lifetimemalloc.dir/build.make runtime/CMakeFiles/lifetimemalloc.dir/build
.PHONY : lifetimemalloc/fast

#=============================================================================
# Target rules for targets named alaska_translate_native

# Build rule for target.
alaska_translate_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_translate_native
.PHONY : alaska_translate_native

# fast build rule for target.
alaska_translate_native/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_translate_native.dir/build.make runtime/CMakeFiles/alaska_translate_native.dir/build
.PHONY : alaska_translate_native/fast

#=============================================================================
# Target rules for targets named alaska_translate_bitcodes

# Build rule for target.
alaska_translate_bitcodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_translate_bitcodes
.PHONY : alaska_translate_bitcodes

# fast build rule for target.
alaska_translate_bitcodes/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_translate_bitcodes.dir/build.make runtime/CMakeFiles/alaska_translate_bitcodes.dir/build
.PHONY : alaska_translate_bitcodes/fast

#=============================================================================
# Target rules for targets named alaska_translate

# Build rule for target.
alaska_translate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_translate
.PHONY : alaska_translate

# fast build rule for target.
alaska_translate/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_translate.dir/build.make runtime/CMakeFiles/alaska_translate.dir/build
.PHONY : alaska_translate/fast

#=============================================================================
# Target rules for targets named alaska_compat_native

# Build rule for target.
alaska_compat_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_compat_native
.PHONY : alaska_compat_native

# fast build rule for target.
alaska_compat_native/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_compat_native.dir/build.make runtime/CMakeFiles/alaska_compat_native.dir/build
.PHONY : alaska_compat_native/fast

#=============================================================================
# Target rules for targets named alaska_compat_bitcodes

# Build rule for target.
alaska_compat_bitcodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_compat_bitcodes
.PHONY : alaska_compat_bitcodes

# fast build rule for target.
alaska_compat_bitcodes/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_compat_bitcodes.dir/build.make runtime/CMakeFiles/alaska_compat_bitcodes.dir/build
.PHONY : alaska_compat_bitcodes/fast

#=============================================================================
# Target rules for targets named alaska_compat

# Build rule for target.
alaska_compat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_compat
.PHONY : alaska_compat

# fast build rule for target.
alaska_compat/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_compat.dir/build.make runtime/CMakeFiles/alaska_compat.dir/build
.PHONY : alaska_compat/fast

#=============================================================================
# Target rules for targets named alaska_stub_native

# Build rule for target.
alaska_stub_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_stub_native
.PHONY : alaska_stub_native

# fast build rule for target.
alaska_stub_native/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_stub_native.dir/build.make runtime/CMakeFiles/alaska_stub_native.dir/build
.PHONY : alaska_stub_native/fast

#=============================================================================
# Target rules for targets named alaska_stub_bitcodes

# Build rule for target.
alaska_stub_bitcodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_stub_bitcodes
.PHONY : alaska_stub_bitcodes

# fast build rule for target.
alaska_stub_bitcodes/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_stub_bitcodes.dir/build.make runtime/CMakeFiles/alaska_stub_bitcodes.dir/build
.PHONY : alaska_stub_bitcodes/fast

#=============================================================================
# Target rules for targets named alaska_stub

# Build rule for target.
alaska_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_stub
.PHONY : alaska_stub

# fast build rule for target.
alaska_stub/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_stub.dir/build.make runtime/CMakeFiles/alaska_stub.dir/build
.PHONY : alaska_stub/fast

#=============================================================================
# Target rules for targets named alaska_test

# Build rule for target.
alaska_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_test
.PHONY : alaska_test

# fast build rule for target.
alaska_test/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_test.dir/build.make runtime/CMakeFiles/alaska_test.dir/build
.PHONY : alaska_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named Alaska

# Build rule for target.
Alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Alaska
.PHONY : Alaska

# fast build rule for target.
Alaska/fast:
	$(MAKE) $(MAKESILENT) -f compiler/CMakeFiles/Alaska.dir/build.make compiler/CMakeFiles/Alaska.dir/build
.PHONY : Alaska/fast

#=============================================================================
# Target rules for targets named install-Alaska

# Build rule for target.
install-Alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-Alaska
.PHONY : install-Alaska

# fast build rule for target.
install-Alaska/fast:
	$(MAKE) $(MAKESILENT) -f compiler/CMakeFiles/install-Alaska.dir/build.make compiler/CMakeFiles/install-Alaska.dir/build
.PHONY : install-Alaska/fast

#=============================================================================
# Target rules for targets named install-Alaska-stripped

# Build rule for target.
install-Alaska-stripped: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-Alaska-stripped
.PHONY : install-Alaska-stripped

# fast build rule for target.
install-Alaska-stripped/fast:
	$(MAKE) $(MAKESILENT) -f compiler/CMakeFiles/install-Alaska-stripped.dir/build.make compiler/CMakeFiles/install-Alaska-stripped.dir/build
.PHONY : install-Alaska-stripped/fast

#=============================================================================
# Target rules for targets named alaska-config

# Build rule for target.
alaska-config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska-config
.PHONY : alaska-config

# fast build rule for target.
alaska-config/fast:
	$(MAKE) $(MAKESILENT) -f compiler/bin/CMakeFiles/alaska-config.dir/build.make compiler/bin/CMakeFiles/alaska-config.dir/build
.PHONY : alaska-config/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... alaska_compat"
	@echo "... alaska_compat_bitcodes"
	@echo "... alaska_stub"
	@echo "... alaska_stub_bitcodes"
	@echo "... alaska_translate"
	@echo "... alaska_translate_bitcodes"
	@echo "... figure10_pdf"
	@echo "... figure11_pdf"
	@echo "... figure12_pdf"
	@echo "... figure7_csv"
	@echo "... figure7_pdf"
	@echo "... figure8_csv"
	@echo "... figure8_pdf"
	@echo "... figure9_pdf"
	@echo "... install-Alaska"
	@echo "... install-Alaska-stripped"
	@echo "... intrinsics_gen"
	@echo "... memcached_alaska"
	@echo "... memcached_sweep_csv"
	@echo "... omp_gen"
	@echo "... redis_alaska"
	@echo "... redis_alaska_large_csv"
	@echo "... rsstracker"
	@echo "... venv"
	@echo "... Alaska"
	@echo "... alaska"
	@echo "... alaska-config"
	@echo "... alaska_compat_native"
	@echo "... alaska_core"
	@echo "... alaska_core_objects"
	@echo "... alaska_core_static"
	@echo "... alaska_sim"
	@echo "... alaska_stub_native"
	@echo "... alaska_test"
	@echo "... alaska_translate_native"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... lifetimemalloc"
.PHONY : help

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named RISCVTargetParserTableGen

# Build rule for target.
RISCVTargetParserTableGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RISCVTargetParserTableGen
.PHONY : RISCVTargetParserTableGen

# fast build rule for target.
RISCVTargetParserTableGen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RISCVTargetParserTableGen.dir/build.make CMakeFiles/RISCVTargetParserTableGen.dir/build
.PHONY : RISCVTargetParserTableGen/fast

#=============================================================================
# Target rules for targets named venv

# Build rule for target.
venv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 venv
.PHONY : venv

# fast build rule for target.
venv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/venv.dir/build.make CMakeFiles/venv.dir/build
.PHONY : venv/fast

#=============================================================================
# Target rules for targets named redis_alaska

# Build rule for target.
redis_alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis_alaska
.PHONY : redis_alaska

# fast build rule for target.
redis_alaska/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_alaska.dir/build.make CMakeFiles/redis_alaska.dir/build
.PHONY : redis_alaska/fast

#=============================================================================
# Target rules for targets named memcached_alaska

# Build rule for target.
memcached_alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memcached_alaska
.PHONY : memcached_alaska

# fast build rule for target.
memcached_alaska/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memcached_alaska.dir/build.make CMakeFiles/memcached_alaska.dir/build
.PHONY : memcached_alaska/fast

#=============================================================================
# Target rules for targets named figure7_csv

# Build rule for target.
figure7_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure7_csv
.PHONY : figure7_csv

# fast build rule for target.
figure7_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure7_csv.dir/build.make CMakeFiles/figure7_csv.dir/build
.PHONY : figure7_csv/fast

#=============================================================================
# Target rules for targets named figure7_pdf

# Build rule for target.
figure7_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure7_pdf
.PHONY : figure7_pdf

# fast build rule for target.
figure7_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure7_pdf.dir/build.make CMakeFiles/figure7_pdf.dir/build
.PHONY : figure7_pdf/fast

#=============================================================================
# Target rules for targets named figure8_csv

# Build rule for target.
figure8_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure8_csv
.PHONY : figure8_csv

# fast build rule for target.
figure8_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure8_csv.dir/build.make CMakeFiles/figure8_csv.dir/build
.PHONY : figure8_csv/fast

#=============================================================================
# Target rules for targets named figure8_pdf

# Build rule for target.
figure8_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure8_pdf
.PHONY : figure8_pdf

# fast build rule for target.
figure8_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure8_pdf.dir/build.make CMakeFiles/figure8_pdf.dir/build
.PHONY : figure8_pdf/fast

#=============================================================================
# Target rules for targets named rsstracker

# Build rule for target.
rsstracker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rsstracker
.PHONY : rsstracker

# fast build rule for target.
rsstracker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rsstracker.dir/build.make CMakeFiles/rsstracker.dir/build
.PHONY : rsstracker/fast

#=============================================================================
# Target rules for targets named figure9_pdf

# Build rule for target.
figure9_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure9_pdf
.PHONY : figure9_pdf

# fast build rule for target.
figure9_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure9_pdf.dir/build.make CMakeFiles/figure9_pdf.dir/build
.PHONY : figure9_pdf/fast

#=============================================================================
# Target rules for targets named figure10_pdf

# Build rule for target.
figure10_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure10_pdf
.PHONY : figure10_pdf

# fast build rule for target.
figure10_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure10_pdf.dir/build.make CMakeFiles/figure10_pdf.dir/build
.PHONY : figure10_pdf/fast

#=============================================================================
# Target rules for targets named redis_alaska_large_csv

# Build rule for target.
redis_alaska_large_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 redis_alaska_large_csv
.PHONY : redis_alaska_large_csv

# fast build rule for target.
redis_alaska_large_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/redis_alaska_large_csv.dir/build.make CMakeFiles/redis_alaska_large_csv.dir/build
.PHONY : redis_alaska_large_csv/fast

#=============================================================================
# Target rules for targets named figure11_pdf

# Build rule for target.
figure11_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure11_pdf
.PHONY : figure11_pdf

# fast build rule for target.
figure11_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure11_pdf.dir/build.make CMakeFiles/figure11_pdf.dir/build
.PHONY : figure11_pdf/fast

#=============================================================================
# Target rules for targets named memcached_sweep_csv

# Build rule for target.
memcached_sweep_csv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 memcached_sweep_csv
.PHONY : memcached_sweep_csv

# fast build rule for target.
memcached_sweep_csv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/memcached_sweep_csv.dir/build.make CMakeFiles/memcached_sweep_csv.dir/build
.PHONY : memcached_sweep_csv/fast

#=============================================================================
# Target rules for targets named figure12_pdf

# Build rule for target.
figure12_pdf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 figure12_pdf
.PHONY : figure12_pdf

# fast build rule for target.
figure12_pdf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/figure12_pdf.dir/build.make CMakeFiles/figure12_pdf.dir/build
.PHONY : figure12_pdf/fast

#=============================================================================
# Target rules for targets named alaska_core_objects

# Build rule for target.
alaska_core_objects: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_core_objects
.PHONY : alaska_core_objects

# fast build rule for target.
alaska_core_objects/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_core_objects.dir/build.make runtime/CMakeFiles/alaska_core_objects.dir/build
.PHONY : alaska_core_objects/fast

#=============================================================================
# Target rules for targets named alaska_core

# Build rule for target.
alaska_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_core
.PHONY : alaska_core

# fast build rule for target.
alaska_core/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_core.dir/build.make runtime/CMakeFiles/alaska_core.dir/build
.PHONY : alaska_core/fast

#=============================================================================
# Target rules for targets named alaska_core_static

# Build rule for target.
alaska_core_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_core_static
.PHONY : alaska_core_static

# fast build rule for target.
alaska_core_static/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_core_static.dir/build.make runtime/CMakeFiles/alaska_core_static.dir/build
.PHONY : alaska_core_static/fast

#=============================================================================
# Target rules for targets named alaska_sim

# Build rule for target.
alaska_sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_sim
.PHONY : alaska_sim

# fast build rule for target.
alaska_sim/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_sim.dir/build.make runtime/CMakeFiles/alaska_sim.dir/build
.PHONY : alaska_sim/fast

#=============================================================================
# Target rules for targets named alaska

# Build rule for target.
alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska
.PHONY : alaska

# fast build rule for target.
alaska/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska.dir/build.make runtime/CMakeFiles/alaska.dir/build
.PHONY : alaska/fast

#=============================================================================
# Target rules for targets named lifetimemalloc

# Build rule for target.
lifetimemalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lifetimemalloc
.PHONY : lifetimemalloc

# fast build rule for target.
lifetimemalloc/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/lifetimemalloc.dir/build.make runtime/CMakeFiles/lifetimemalloc.dir/build
.PHONY : lifetimemalloc/fast

#=============================================================================
# Target rules for targets named alaska_translate_native

# Build rule for target.
alaska_translate_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_translate_native
.PHONY : alaska_translate_native

# fast build rule for target.
alaska_translate_native/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_translate_native.dir/build.make runtime/CMakeFiles/alaska_translate_native.dir/build
.PHONY : alaska_translate_native/fast

#=============================================================================
# Target rules for targets named alaska_translate_bitcodes

# Build rule for target.
alaska_translate_bitcodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_translate_bitcodes
.PHONY : alaska_translate_bitcodes

# fast build rule for target.
alaska_translate_bitcodes/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_translate_bitcodes.dir/build.make runtime/CMakeFiles/alaska_translate_bitcodes.dir/build
.PHONY : alaska_translate_bitcodes/fast

#=============================================================================
# Target rules for targets named alaska_translate

# Build rule for target.
alaska_translate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_translate
.PHONY : alaska_translate

# fast build rule for target.
alaska_translate/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_translate.dir/build.make runtime/CMakeFiles/alaska_translate.dir/build
.PHONY : alaska_translate/fast

#=============================================================================
# Target rules for targets named alaska_compat_native

# Build rule for target.
alaska_compat_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_compat_native
.PHONY : alaska_compat_native

# fast build rule for target.
alaska_compat_native/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_compat_native.dir/build.make runtime/CMakeFiles/alaska_compat_native.dir/build
.PHONY : alaska_compat_native/fast

#=============================================================================
# Target rules for targets named alaska_compat_bitcodes

# Build rule for target.
alaska_compat_bitcodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_compat_bitcodes
.PHONY : alaska_compat_bitcodes

# fast build rule for target.
alaska_compat_bitcodes/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_compat_bitcodes.dir/build.make runtime/CMakeFiles/alaska_compat_bitcodes.dir/build
.PHONY : alaska_compat_bitcodes/fast

#=============================================================================
# Target rules for targets named alaska_compat

# Build rule for target.
alaska_compat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_compat
.PHONY : alaska_compat

# fast build rule for target.
alaska_compat/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_compat.dir/build.make runtime/CMakeFiles/alaska_compat.dir/build
.PHONY : alaska_compat/fast

#=============================================================================
# Target rules for targets named alaska_stub_native

# Build rule for target.
alaska_stub_native: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_stub_native
.PHONY : alaska_stub_native

# fast build rule for target.
alaska_stub_native/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_stub_native.dir/build.make runtime/CMakeFiles/alaska_stub_native.dir/build
.PHONY : alaska_stub_native/fast

#=============================================================================
# Target rules for targets named alaska_stub_bitcodes

# Build rule for target.
alaska_stub_bitcodes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_stub_bitcodes
.PHONY : alaska_stub_bitcodes

# fast build rule for target.
alaska_stub_bitcodes/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_stub_bitcodes.dir/build.make runtime/CMakeFiles/alaska_stub_bitcodes.dir/build
.PHONY : alaska_stub_bitcodes/fast

#=============================================================================
# Target rules for targets named alaska_stub

# Build rule for target.
alaska_stub: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_stub
.PHONY : alaska_stub

# fast build rule for target.
alaska_stub/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_stub.dir/build.make runtime/CMakeFiles/alaska_stub.dir/build
.PHONY : alaska_stub/fast

#=============================================================================
# Target rules for targets named alaska_test

# Build rule for target.
alaska_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska_test
.PHONY : alaska_test

# fast build rule for target.
alaska_test/fast:
	$(MAKE) $(MAKESILENT) -f runtime/CMakeFiles/alaska_test.dir/build.make runtime/CMakeFiles/alaska_test.dir/build
.PHONY : alaska_test/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named Alaska

# Build rule for target.
Alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Alaska
.PHONY : Alaska

# fast build rule for target.
Alaska/fast:
	$(MAKE) $(MAKESILENT) -f compiler/CMakeFiles/Alaska.dir/build.make compiler/CMakeFiles/Alaska.dir/build
.PHONY : Alaska/fast

#=============================================================================
# Target rules for targets named install-Alaska

# Build rule for target.
install-Alaska: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-Alaska
.PHONY : install-Alaska

# fast build rule for target.
install-Alaska/fast:
	$(MAKE) $(MAKESILENT) -f compiler/CMakeFiles/install-Alaska.dir/build.make compiler/CMakeFiles/install-Alaska.dir/build
.PHONY : install-Alaska/fast

#=============================================================================
# Target rules for targets named install-Alaska-stripped

# Build rule for target.
install-Alaska-stripped: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-Alaska-stripped
.PHONY : install-Alaska-stripped

# fast build rule for target.
install-Alaska-stripped/fast:
	$(MAKE) $(MAKESILENT) -f compiler/CMakeFiles/install-Alaska-stripped.dir/build.make compiler/CMakeFiles/install-Alaska-stripped.dir/build
.PHONY : install-Alaska-stripped/fast

#=============================================================================
# Target rules for targets named alaska-config

# Build rule for target.
alaska-config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alaska-config
.PHONY : alaska-config

# fast build rule for target.
alaska-config/fast:
	$(MAKE) $(MAKESILENT) -f compiler/bin/CMakeFiles/alaska-config.dir/build.make compiler/bin/CMakeFiles/alaska-config.dir/build
.PHONY : alaska-config/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... RISCVTargetParserTableGen"
	@echo "... acc_gen"
	@echo "... alaska_compat"
	@echo "... alaska_compat_bitcodes"
	@echo "... alaska_stub"
	@echo "... alaska_stub_bitcodes"
	@echo "... alaska_translate"
	@echo "... alaska_translate_bitcodes"
	@echo "... figure10_pdf"
	@echo "... figure11_pdf"
	@echo "... figure12_pdf"
	@echo "... figure7_csv"
	@echo "... figure7_pdf"
	@echo "... figure8_csv"
	@echo "... figure8_pdf"
	@echo "... figure9_pdf"
	@echo "... install-Alaska"
	@echo "... install-Alaska-stripped"
	@echo "... intrinsics_gen"
	@echo "... memcached_alaska"
	@echo "... memcached_sweep_csv"
	@echo "... omp_gen"
	@echo "... redis_alaska"
	@echo "... redis_alaska_large_csv"
	@echo "... rsstracker"
	@echo "... venv"
	@echo "... Alaska"
	@echo "... alaska"
	@echo "... alaska-config"
	@echo "... alaska_compat_native"
	@echo "... alaska_core"
	@echo "... alaska_core_objects"
	@echo "... alaska_core_static"
	@echo "... alaska_sim"
	@echo "... alaska_stub_native"
	@echo "... alaska_test"
	@echo "... alaska_translate_native"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... lifetimemalloc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

